version: "2"
services:
  <%= projectName %>:
    container_name: <%= projectName %>
    hostname: <%= projectName %>
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    volumes:
      - <%= projectName %>-fs:/app:nocopy
    networks:
      default:
        aliases:
          - <%= projectName %>
    ports:
      - 3000:3000
      - 9229:9229

volumes:
  <%= projectName %>-fs:
    external: true

networks:
  default:
